#!/bin/sh
set -eu

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname "$0")" && pwd)"
# shellcheck source=common.sh
. "${SCRIPT_DIR}/common.sh"

load_target_env

cat <<EOF
DEPLOY_TARGET=${DEPLOY_TARGET}
SERVER_REF=${SERVER_REF}
SSH_TARGET=${SSH_TARGET}
SSH_PORT=${SSH_PORT}
SCP_EXTRA_OPTS=${SCP_EXTRA_OPTS}
REMOTE_BINARY=${REMOTE_BINARY}
REMOTE_TMP=${REMOTE_TMP}
REMOTE_WEB_ZIP=${REMOTE_WEB_ZIP}
REMOTE_BACKUP_DIR=${REMOTE_BACKUP_DIR}
REMOTE_SERVICE=${REMOTE_SERVICE}
REMOTE_WEB_DIR=${REMOTE_WEB_DIR}
REMOTE_TEMPLATE=${REMOTE_TEMPLATE}
LOCAL_BINARY=${LOCAL_BINARY}
LOCAL_WEB_ZIP=${LOCAL_WEB_ZIP}
PROTECT_CRITICAL_GATEWAY=${PROTECT_CRITICAL_GATEWAY}
EOF
