<template>
    <details class="advanced-tools" @toggle="handleToggle">
        <summary>{{ $gettext('高级网络工具') }}<small>{{ $gettext('按需诊断、审计和策略备份') }}</small></summary>
        <PageState v-if="loading" kind="loading" :title="$gettext('正在读取高级能力')" />
        <p v-else-if="error" class="message error">{{ error }} <button type="button" @click="load">{{ $gettext('重试') }}</button></p>
        <div v-else-if="loaded" class="advanced-body">
            <section><h5>{{ $gettext('能力与兼容性') }}</h5><div class="capabilities"><div v-for="(capability, key) in capabilities" :key="key"><span>{{ capabilityLabel(key) }}</span><b :class="capability.state">{{ stateLabel(capability.state) }}</b><small>{{ capabilityReason(capability) }}</small></div></div></section>
            <section v-if="primaryAddress"><h5>{{ $gettext('设备管理入口') }}</h5><p>{{ $gettext('只探测设备当前局域网地址和常用管理端口；不会扫描其他地址，也不会跟随跳转。') }}</p><div class="probe-actions"><button type="button" :disabled="probing" @click="probe('http',80)">HTTP · 80</button><button type="button" :disabled="probing" @click="probe('https',443)">HTTPS · 443</button></div><p v-if="probeMessage" class="message" :class="probeKind">{{ probeMessage }}</p></section>
            <section><h5>{{ $gettext('最近变更') }}</h5><p class="bounded-note">{{ $gettext('最近变更仅在展开后读取，记录数量有上限。') }}</p><ul v-if="events.length"><li v-for="event in events" :key="event.id"><span>{{ actionLabel(event.action) }} · {{ resourceLabel(event.resource) }}</span><time>{{ new Date(event.at).toLocaleString() }}</time></li></ul><p v-else>{{ $gettext('暂无与此设备有关的审计事件') }}</p></section>
            <section><h5>{{ $gettext('新设备与网关切换通知') }}</h5><p>{{ $gettext('此设置对本路由器全部设备生效。可选 Webhook 默认关闭，只发送事件类型、时间和设备标识，不发送 DNS 内容。') }}</p><label class="webhook-toggle"><input v-model="webhookEnabled" type="checkbox" />{{ webhookEnabled ? $gettext('启用通知') : $gettext('不启用通知') }}</label><input v-if="webhookEnabled" v-model.trim="webhookURL" class="webhook-url" type="url" inputmode="url" :placeholder="webhookConfigured ? $gettext('已配置；如需更换请输入新地址') : 'https://example.com/webhook'" /><div class="webhook-actions"><button type="button" :disabled="webhookSaving || (webhookEnabled && !webhookURL)" @click="saveWebhook">{{ webhookSaving ? $gettext('正在保存…') : $gettext('保存通知设置') }}</button><small v-if="webhookConfigured && webhookEnabled">{{ $gettext('现有地址已隐藏；更换时需重新输入。') }}</small></div><p v-if="webhookMessage" class="message" :class="webhookKind">{{ webhookMessage }}</p></section>
            <section><h5>{{ $gettext('策略备份与恢复') }}</h5><p>{{ $gettext('导出和恢复设备分组、单设备例外与流量额度；地址、路线、限速和防火墙规则不会被替换。') }}</p><div class="bundle-actions"><button type="button" @click="exportBundle">{{ $gettext('导出策略包') }}</button><label><span>{{ $gettext('选择策略包') }}</span><input type="file" accept="application/json,.json" @change="prepareImport" /></label></div><div v-if="importPlan" class="import-plan"><strong>{{ $gettext('预检通过') }}</strong><span>{{ importPlan.groupCount }} {{ $gettext('个分组') }} · {{ importPlan.devicePolicyCount }} {{ $gettext('个设备例外') }} · {{ importPlan.quotaCount }} {{ $gettext('个额度') }}</span><small v-for="warning in importPlan.warnings" :key="warning">{{ warningLabel(warning) }}</small><button type="button" class="danger" :disabled="importing" @click="applyImport">{{ importing ? $gettext('正在恢复…') : $gettext('确认恢复') }}</button></div><p v-if="importMessage" class="message" :class="importKind">{{ importMessage }}</p></section>
        </div>
    </details>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import { useGettext } from '/@/plugins/i18n'
import request from '/@/request'
import PageState from './pageState.vue'

const props = defineProps<{ device: any }>()
const { $gettext } = useGettext()
const loading=ref(false),loaded=ref(false),error=ref(''),capabilities=ref<Record<string,any>>({}),events=ref<any[]>([]),probing=ref(false),probeMessage=ref(''),probeKind=ref<'success'|'error'>('success'),webhookEnabled=ref(false),webhookConfigured=ref(false),webhookURL=ref(''),webhookSaving=ref(false),webhookMessage=ref(''),webhookKind=ref<'success'|'error'>('success'),importPlan=ref<any>(null),importBundle=ref<any>(null),importing=ref(false),importMessage=ref(''),importKind=ref<'success'|'error'>('success')
const primaryAddress=computed(()=>props.device.addresses?.current?.find((address:any)=>address.family===4)?.address || props.device.addresses?.current?.[0]?.address || '')
const capabilityLabel=(key:string)=>({ipv6_reservation:$gettext('IPv6 地址策略'),connection_insights:$gettext('连接洞察'),dns_insights:$gettext('DNS 洞察'),management_probe:$gettext('管理入口探测'),segmentation:$gettext('来宾 / IoT 分段'),multi_wan:$gettext('多 WAN 策略'),identification_updates:$gettext('识别规则更新')} as Record<string,string>)[key]||key
const stateLabel=(state:string)=>({available:$gettext('可用'),disabled:$gettext('未启用'),not_installed:$gettext('未安装'),unsupported:$gettext('不支持'),error:$gettext('异常')} as Record<string,string>)[state]||$gettext('异常')
const capabilityReason=(capability:any)=>({firmware_contract_not_verified:$gettext('当前固件尚未验证，未展示假控件'),bandix_not_installed:$gettext('安装兼容的 Bandix 后才可用'),adapter_contract_not_verified:$gettext('已检测到 Bandix，但当前固件尚未启用经验证的连接洞察适配器'),dns_privacy_default:$gettext('默认不采集或记录 DNS 名称'),segmentation_adapter_not_installed:$gettext('未安装分段适配器'),multi_wan_adapter_not_installed:$gettext('未安装多 WAN 适配器'),built_in_rules_only:$gettext('当前仅使用内置可回滚规则'),hardware_offload_enabled:$gettext('硬件卸载已开启，统计可能不完整')} as Record<string,string>)[capability.reason]||capability.detail||''
const actionLabel=(value:string)=>({policy_changed:$gettext('策略变更'),address_conflict:$gettext('地址冲突'),gateway_failover:$gettext('网关切换'),probe:$gettext('入口探测'),new_device:$gettext('发现新设备'),device_online:$gettext('设备上线'),device_offline:$gettext('设备离线'),quota_exceeded:$gettext('额度已用尽')} as Record<string,string>)[value]||value
const resourceLabel=(value:string)=>({device:$gettext('设备状态'),device_policy:$gettext('设备控制'),device_network_policy:$gettext('地址与路线'),address_reservation:$gettext('地址保留'),gateway_assignment:$gettext('上网路线'),floating_gateway:$gettext('浮动网关'),device_groups:$gettext('设备分组'),network_rules:$gettext('网络规则'),traffic_quota:$gettext('流量额度'),management_probe:$gettext('管理入口'),policy_bundle:$gettext('策略备份')} as Record<string,string>)[value]||value
const warningLabel=(value:string)=>value==='Import replaces device groups and traffic quotas only; address, route, speed and firewall rules are unchanged.'?$gettext('只会替换设备分组、设备例外与流量额度；地址、路线、限速和防火墙规则保持不变。'):value
const load=async()=>{loading.value=true;error.value='';try{const response=await request.DeviceMangement.advancedNetworkV2.GET(props.device.deviceId);if(response.data.result?.error)throw new Error(response.data.result.error.message);capabilities.value=response.data.result?.capabilities||{};events.value=response.data.result?.events||[];const webhook=response.data.result?.webhook||{};webhookEnabled.value=Boolean(webhook.enabled);webhookConfigured.value=webhook.url==='configured';loaded.value=true}catch(reason:any){error.value=reason?.message||$gettext('高级能力读取失败')}finally{loading.value=false}}
const handleToggle=(event:Event)=>{if((event.target as HTMLDetailsElement).open&&!loaded.value&&!loading.value)load()}
const probe=async(scheme:string,port:number)=>{probing.value=true;probeMessage.value='';try{const response=await request.DeviceMangement.advancedNetworkV2.PROBE({deviceId:props.device.deviceId,address:primaryAddress.value,scheme,port});const result=response.data.result;if(result?.error)throw new Error(result.error.message);probeKind.value='success';probeMessage.value=`${$gettext('可访问')} · ${result.url} · HTTP ${result.statusCode} · ${result.durationMs} ms`}catch(reason:any){probeKind.value='error';probeMessage.value=reason?.message||$gettext('该入口当前不可访问')}finally{probing.value=false}}
const saveWebhook=async()=>{webhookSaving.value=true;webhookMessage.value='';try{const response=await request.DeviceMangement.advancedNetworkV2.WEBHOOK(webhookEnabled.value?{enabled:true,url:webhookURL.value,events:['new_device','gateway_failover']}:{enabled:false});if(response.data.result?.error)throw new Error(response.data.result.error.message);webhookKind.value='success';webhookMessage.value=webhookEnabled.value?$gettext('通知已启用'):$gettext('通知已关闭');webhookConfigured.value=webhookEnabled.value;webhookURL.value=''}catch(reason:any){webhookKind.value='error';webhookMessage.value=reason?.message||$gettext('通知设置保存失败')}finally{webhookSaving.value=false}}
const exportBundle=async()=>{try{const response=await request.DeviceMangement.advancedNetworkV2.EXPORT();if(response.data.result?.error)throw new Error(response.data.result.error.message);const blob=new Blob([JSON.stringify(response.data.result.bundle,null,2)],{type:'application/json'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`quickstart-policy-${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(link.href)}catch(reason:any){importKind.value='error';importMessage.value=reason?.message||$gettext('导出失败')}}
const prepareImport=async(event:Event)=>{importPlan.value=null;importMessage.value='';try{const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;const bundle=JSON.parse(await file.text());const response=await request.DeviceMangement.advancedNetworkV2.IMPORT_PLAN({bundle});if(response.data.result?.error)throw new Error(response.data.result.error.message);importBundle.value=bundle;importPlan.value=response.data.result.plan}catch(reason:any){importKind.value='error';importMessage.value=reason?.message||$gettext('策略包预检失败，未写入任何配置')}}
const applyImport=async()=>{if(!importBundle.value||!importPlan.value||!window.confirm($gettext('确认恢复这个策略包？现有分组和额度会被替换。')))return;importing.value=true;try{const response=await request.DeviceMangement.advancedNetworkV2.IMPORT_APPLY({bundle:importBundle.value,planChecksum:importPlan.value.checksum,expectedGroupVersion:importPlan.value.groupVersion,confirmed:true});if(response.data.result?.error)throw new Error(response.data.result.error.message);importKind.value='success';importMessage.value=$gettext('策略包已恢复');importPlan.value=null;await load()}catch(reason:any){importKind.value='error';importMessage.value=reason?.message||$gettext('恢复失败，原配置已回滚')}finally{importing.value=false}}
</script>

<style lang="scss" scoped>
.advanced-tools { margin-top: 12px; border: 1px solid rgba(127,127,127,.16); border-radius: 8px; }.advanced-tools > summary { display: flex; justify-content: space-between; gap: 8px; padding: 11px; color: #553afe; cursor: pointer; font-weight: 600; }.advanced-tools > summary small { color: inherit; opacity: .65; font-weight: 400; }.advanced-body { padding: 0 11px 11px; }.advanced-body section { padding: 12px 0; border-top: 1px solid rgba(127,127,127,.13); }.advanced-body h5 { margin: 0 0 7px; font-size: 13px; }.advanced-body p { margin: 6px 0; opacity: .7; }.capabilities { display: grid; gap: 6px; }.capabilities > div { display: grid; grid-template-columns: 1fr auto; gap: 2px 8px; padding: 7px; background: rgba(127,127,127,.045); border-radius: 6px; }.capabilities small { grid-column: 1 / -1; opacity: .62; }.capabilities b { color: #7a5b00; }.capabilities b.available { color: #176b45; }.capabilities b.unavailable,.capabilities b.not_installed { color: #777; }.probe-actions,.bundle-actions,.webhook-actions { display: flex; flex-wrap: wrap; align-items: center; gap: 7px; }.advanced-tools button,.bundle-actions label { padding: 6px 9px; color: #553afe; background: transparent; border: 1px solid rgba(85,58,254,.3); border-radius: 6px; cursor: pointer; }.bundle-actions label input { display: none; }.webhook-toggle { display: flex; align-items: center; gap: 7px; margin: 8px 0; }.webhook-url { box-sizing: border-box; width: 100%; margin-bottom: 8px; padding: 8px; border: 1px solid rgba(127,127,127,.25); border-radius: 6px; }.webhook-actions small { opacity: .62; }.advanced-body ul { padding: 0; list-style: none; }.advanced-body li { display: flex; justify-content: space-between; gap: 8px; padding: 6px 0; }.advanced-body time { opacity: .55; font-size: 11px; }.import-plan { display: grid; gap: 5px; margin-top: 9px; padding: 9px; background: rgba(85,58,254,.05); border-radius: 7px; }.import-plan small { opacity: .65; }.advanced-tools .danger { color: #fff; background: #a13c3c; border-color: #a13c3c; }.message { padding: 7px; border-radius: 6px; }.message.success { color: #176b45; background: rgba(38,162,105,.1); }.message.error { color: #9b3b16; background: #fff1e8; }
@media(max-width:420px){.advanced-tools > summary,.advanced-body li{flex-direction:column}.capabilities > div{grid-template-columns:1fr}.capabilities small{grid-column:auto}}
</style>
